### ISSUE TITLE
@web-vue/components 下不存在 icon 组件

### ISSUE THREAD

**Issue by qiqingfu** [arco-design/arco-design-vue#106]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** arco-design-vue@2.1.0
- **系统版本:** mac
- **浏览器版本:** 版本 95.0.4638.69（正式版本） (x86_64)
- **复现地址:** https://github.com/arco-design/arco-design-vue/releases/tag/2.1.0

## 额外补充
我再 GitHub 远程仓库查看 https://github.com/arco-design/arco-design-vue/tree/main/packages/web-vue/components，也发现没有 icon 目录，请问是什么原因呢

## 预期结果
期望可以正常预览站点，结果报错。

/Users/wmmqy/Desktop/arco-design-vue/packages/arco-vue-docs/index.ts
  4:25  error  Unable to resolve path to module '@web-vue/components/icon'  import/no-unresolved

✖ 1 problem (1 error, 0 warnings)
/Users/wmmqy/Desktop/arco-design-vue/packages/arco-vue-docs/index.ts
    at formatError (/Users/wmmqy/Desktop/arco-design-vue/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:42189:46)
    at TransformContext.error (/Users/wmmqy/Desktop/arco-design-vue/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:42185:19)
    at TransformContext.transform (/Users/wmmqy/Desktop/arco-design-vue/node_modules/vite-plugin-eslint/dist/index.js:87:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.transform (/Users/wmmqy/Desktop/arco-design-vue/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:42396:30)
    at async doTransform (/Users/wmmqy/Desktop/arco-design-vue/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:56797:29

## 复现步骤
Fork 此仓库，从 main 创建分支。

新功能实现请发 pull request 到 feature 分支。其他更改发到 main 分支。

在仓库根目录下执行 lerna bootstrap 安装子包依赖。

在仓库根目录下执行 npm run init。

执行 npm run start 启动和预览站点.

**Comment by kirazxyun** [comment]
你好，我们从 lerna 改到 yarn workspace 来管理 monorepo 了。可以尝试一下最新的启动流程试试
![image](https://user-images.githubusercontent.com/10192144/140679381-b9fdcd37-2aee-48f2-9995-891f6e0e5c74.png)

重新启动之前注意清理一下 node_modules 哦～

**Comment by qiqingfu** [comment]
@kirazxyun 好的，感谢回复，我再试一下

**Comment by qiqingfu** [comment]
@kirazxyun 还是报这个错误

```js
[plugin:vite:eslint] /Users/wmmqy/Desktop/arco-design-vue/packages/arco-vue-docs/index.ts
  4:25  error  Unable to resolve path to module '@web-vue/components/icon'  import/no-unresolved
```

components 目录下没有 icon 组件，其他模块有引用 icon 组件，所以导致报错。 components/icon 是动态生成的吗?

**Comment by kirazxyun** [comment]
![image](https://user-images.githubusercontent.com/10192144/140749389-20aac75c-65a2-4ed4-8f36-d135ab3c64a3.png)
可以尝试运行一下这个命令试试

**Comment by qiqingfu** [comment]
@kirazxyun 现在可以正常运行了，感谢指点。是个奇怪的问题，我在根目录运行 `npm run init`，@arco-design/web-vue 的 init 脚本执行，应该会生成 icon 的，结果却没有。也可能是我环境的问题，后续我再研究一下
