### ISSUE TITLE
build 报错（node 12.22.11）

### ISSUE THREAD

**Issue by Yuxiaogang-Gavin** [arco-design/arco-design-vue#1130]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.27.0
- **浏览器版本:** chrome101.0.4951.54

## 额外补充
D:\www\arco_demo\node_modules\_vscode-jsonrpc@8.0.1@vscode-jsonrpc\lib\common\linkedMap.js:40
        return this._head?.value;
                          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\www\arco_demo\node_modules\_vscode-jsonrpc@8.0.1@vscode-jsonrpc\lib\common\api.js:37:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! arco-design-pro-vue@1.0.0 build: `vue-tsc --noEmit && vite build --config ./config/vite.config.prod.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the arco-design-pro-vue@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Program Files\nodejs\node_cache\_logs\2022-05-15T00_31_08_356Z-debug.log

**Comment by flsion** [comment]
@Yuxiaogang-Gavin 这个是构建配置的问题，不支持 ?. 的形式。检查下 ts 或者 bable 配置

**Comment by hehehai** [comment]
@Yuxiaogang-Gavin 升级下 typescript 版本再试下

**Comment by hehehai** [comment]
该问题长期无跟踪暂时关闭，后面有补充再可开启。
