### ISSUE TITLE
<a-image-preview-action/> 操作项组件不存在？

### ISSUE THREAD

**Issue by SoXunwa** [arco-design/arco-design-vue#2171]
### 开发环境：
`
      "dependencies": {
        "@arco-design/web-vue": "^2.43.2",
        "@icon-park/vue-next": "^1.4.2",
        "axios": "^1.3.4",
        "vue": "^3.2.47",
        "vue-router": "^4.1.6"
      },
      "devDependencies": {
        "@vitejs/plugin-vue": "^4.0.0",
        "babel-plugin-import": "^1.13.6",
        "typescript": "^4.9.5",
        "unplugin-auto-import": "^0.13.0",
        "unplugin-vue-components": "^0.22.12",
        "vite": "^4.1.4",
        "vue-tsc": "^1.2.0"
      }
`

### 项目代码：
` 

            <a-image-preview v-model:visible="previewProps.visible" v-model:src="previewProps.src">
                <template #actions>
                    <a-image-preview-action><icon-delete /></a-image-preview-action>
                </template>
            </a-image-preview>
`

### Vite 错误提示：
`
23:23:23 [vite] Internal server error: Failed to resolve import "@arco-design/web-vue/es/image-preview-action/style/css.js" from "src\components\shop\file\explorer-folder.vue". Does the file exist?
  Plugin: vite:import-analysis
  File: D:/Developing_Code/java_project/micro-store/admin-client/src/components/shop/file/explorer-folder.vue:5:94
  3  |  import { Popconfirm as __unplugin_components_7 } from '@arco-design/web-vue';import '@arco-design/web-vue/es/popconfirm/style/css.js';
  4  |  import { ImagePreview as __unplugin_components_6 } from '@arco-design/web-vue';import '@arco-design/web-vue/es/image/style/css.js';
  5  |  import { ImagePreviewAction as __unplugin_components_5 } from '@arco-design/web-vue';import '@arco-design/web-vue/es/image-preview-action/style/css.js';
     |                                                                                               ^
  6  |  import { Space as __unplugin_components_4 } from '@arco-design/web-vue';import '@arco-design/web-vue/es/space/style/css.js';
  7  |  import { InputGroup as __unplugin_components_3 } from '@arco-design/web-vue';import '@arco-design/web-vue/es/input/style/css.js';
      at formatError (file:///D:/Developing_Code/java_project/micro-store/admin-client/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41418:46)
      at TransformContext.error (file:///D:/Developing_Code/java_project/micro-store/admin-client/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41414:19)
      at normalizeUrl (file:///D:/Developing_Code/java_project/micro-store/admin-client/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39706:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async TransformContext.transform (file:///D:/Developing_Code/java_project/micro-store/admin-client/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39840:47)
      at async Object.transform (file:///D:/Developing_Code/java_project/micro-store/admin-client/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41685:30)
      at async loadAndTransform (file:///D:/Developing_Code/java_project/micro-store/admin-client/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39479:29)
`

**Comment by sakura-he** [comment]
+1

**Comment by JamieDIng** [comment]
我是build遇到过当时是手动 import 这个组件去使用解决了
