### ISSUE TITLE
npm run init failed, [vite:svgr] Cannot read properties of undefined (reading 'transform')

### ISSUE THREAD

**Issue by Loongphy** [arco-design/arco-design-vue#2588]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.49.1
- **Browser:** chrome116.0.0.0

## Extra info
```
[vite:svgr] Cannot read properties of undefined (reading 'transform')
file: /workspaces/arco-design-vue/node_modules/@arco-materials/site-navbar-new/es/assets/logo/arco.svg
error during build:
TypeError: Cannot read properties of undefined (reading 'transform')
    at Object.transform (/workspaces/arco-design-vue/packages/arco-vue-docs-navbar/vite.config.ts:48:50)
    at async transform (/workspaces/arco-design-vue/node_modules/rollup/dist/shared/rollup.js:22042:16)
    at async ModuleLoader.addModuleSource (/workspaces/arco-design-vue/node_modules/rollup/dist/shared/rollup.js:22267:30)
````

**Comment by Loongphy** [comment]
固定 `packages/arco-vue-docs-navbar/package.json`  Vite  版本
```json
"vite": "2.5.6"
```
