### ISSUE TITLE
莫名其妙的报错

### ISSUE THREAD

**Issue by sz-xiaoming** [arco-design/arco-design-vue#2749]
进入页面然后直接报这个错误，线上也有类似的问题，但能使用，本地运行访问的时候问题就更严重，直接不能用

upload.js:184 Uncaught (in promise) TypeError: fileList2.map is not a function
    at checkFileList (upload.js:184:66)
    at watch.immediate (upload.js:200:9)
    at callWithErrorHandling (runtime-core.esm-bundler.js:173:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:182:21)
    at job (runtime-core.esm-bundler.js:1812:17)
    at doWatch (runtime-core.esm-bundler.js:1855:13)
    at watch (runtime-core.esm-bundler.js:1688:12)
    at setup (upload.js:198:5)
    at callWithErrorHandling (runtime-core.esm-bundler.js:173:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7265:29)

**Comment by sz-xiaoming** [comment]
点进去查看checkFileList (upload.js:184:66)   是ui组件upload.js的问题  arco-design版本是2.52.0

**Comment by Przeblysk** [comment]
给个最小复现demo吧
