### ISSUE TITLE
使用了useFormItem后，打包报错css.js无法import

### ISSUE THREAD

**Issue by fairySusan** [arco-design/arco-design-vue#2984]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.49.2
- **Framework version:**  "vue": "^3.2.37",
- **Browser:** chrome121.0.0.0

## Steps to reproduce
[vite]: Rollup failed to resolve import "@arco-design/web-vue/es/use-form-item/style/css.js" from "src/components/condition-tree/condition-category/custom-form-textarea.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "@arco-design/web-vue/es/use-form-item/style/css.js" from "src/components/condition-tree/condition-category/custom-form-textarea.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (D:\workspace\data-manage-web\node_modules\vite\dist\node\chunks\dep-689425f3.js:41797:19)
    at onwarn (D:\workspace\data-manage-web\node_modules\vite\dist\node\chunks\dep-689425f3.js:41613:13)
    at Object.onwarn (D:\workspace\data-manage-web\node_modules\rollup\dist\shared\rollup.js:23216:13)
    at ModuleLoader.handleResolveId (D:\workspace\data-manage-web\node_modules\rollup\dist\shared\rollup.js:22466:26)
    at D:\workspace\data-manage-web\node_modules\rollup\dist\shared\rollup.js:22427:26
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by fairySusan** [comment]
在config/plugin/styleImport.js 里 ignoreList列表里加上'use-form-item'就解决了
