### ISSUE TITLE
使用vitePluginForArco设置主题在build时报错

### ISSUE THREAD

**Issue by PanZhangOne** [arco-design/arco-design-vue#3221]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.55.3
- **框架版本:** vue3.4.27
- **浏览器版本:** chrome126.0.0.0

## 额外补充
x Build failed in 4.49s
error during build:
RollupError: Expected ';', '}' or <eof>
    at getRollupError (file:///Users/xx/Desktop/Project/fix/erp_system_child_fix/node_modules/.pnpm/rollup@4.17.2/node_modules/rollup/dist/es/shared/parseAst.js:394:41)
    at ParseError.initialise (file:///Users/xx/Desktop/Project/fix/erp_system_child_fix/node_modules/.pnpm/rollup@4.17.2/node_modules/rollup/dist/es/shared/node-entry.js:11332:28)
    at convertNode (file:///Users/xx/Desktop/Project/fix/erp_system_child_fix/node_modules/.pnpm/rollup@4.17.2/node_modules/rollup/dist/es/shared/node-entry.js:13082:10)
    at convertProgram (file:///Users/xx/Desktop/Project/fix/erp_system_child_fix/node_modules/.pnpm/rollup@4.17.2/node_modules/rollup/dist/es/shared/node-entry.js:12399:12)
    at Module.setSource (file:///Users/xx/Desktop/Project/fix/erp_system_child_fix/node_modules/.pnpm/rollup@4.17.2/node_modules/rollup/dist/es/shared/node-entry.js:14243:24)
    at async ModuleLoader.addModuleSource (file:///Users/xx/Desktop/Project/fix/erp_system_child_fix/node_modules/.pnpm/rollup@4.17.2/node_modules/rollup/dist/es/shared/node-entry.js:18896:13)
 ELIFECYCLE  Command failed with exit code 1.

**Comment by PanZhangOne** [comment]
vite插件配置如下：
```javascript
    plugins: [
      injectFilePath(),
      tsconfigPaths(),
      vue(),
      vueJsx(),
      svgLoader(),
      AutoImport({
        resolvers: [ArcoResolver()],
      }),
      Components({
        resolvers: [
          ArcoResolver({
            sideEffect: true,
          }),
        ],
      }),
      vitePluginForArco({
        theme: '@arco-themes/vue-yjjmh-element-color',
      }),
    ]
```
